spring:
  config:
    import:
      - classpath:config-monitoring-dev.yml
      - classpath:dev-secret.yml

  datasource:
    url: jdbc:mysql://${secret.datasource.host}:${secret.datasource.port}/${secret.datasource.database}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${secret.datasource.username}
    password: ${secret.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      cluster:
        nodes: ${secret.redis.host}:${secret.redis.port}
        max-redirects: 3
      ssl:
        enabled: true

stt:
  azure:
    enabled: true

cors:
  origin-urls: ${secret.cors.origin}
