spring:
  config:
    import:
      - classpath:config-monitoring-dev.yml

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:13306}/${MYSQL_DATABASE:debate}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER:debate}
    password: ${MYSQL_PASSWORD:debate}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:16379}

cors:
  origin-urls: ["http://localhost:3000", "http://localhost:5173"]
