spring:
  application:
    name: app-debate
  profiles:
    active: local
  config:
    import:
      - classpath:config-stt.yml
      - classpath:config-llm.yml

  jpa:
    open-in-view: false

  cache:
    type: redis

  flyway:
    enabled: false

  ai:
    chat:
      client:
        enabled: true

llm:
  enabled: true
