spring:
  ai:
    bedrock:
      converse:
        aws:
          access-key: ${secret.aws.access-key-id}
          secret-key: ${secret.aws.secret-access-key}
          region: ${secret.aws.region}

llm:
  refine:
    model: us.amazon.nova-2-lite-v1:0
  extract:
    model: us.amazon.nova-pro-v1:0
