plugins {
	id 'java-library'
}

dependencies {
	// Azure Speech SDK — 안드로이드 패키징이 기본이므로 @jar로 JAR 강제 지정
	implementation 'com.microsoft.cognitiveservices.speech:client-sdk:1.41.1@jar'

	//Slf4j 기반 로깅
	implementation 'org.slf4j:slf4j-api'

	//Spring Boot 자동 주입 기능
	compileOnly 'org.springframework.boot:spring-boot-autoconfigure'
}
