plugins {
    id 'java-library'
}

dependencies {
    implementation project(':common')
    implementation 'com.microsoft.cognitiveservices.speech:client-sdk:1.41.1@jar'

    compileOnly 'org.springframework.boot:spring-boot-autoconfigure'
    compileOnly 'org.springframework:spring-context'

    implementation 'org.slf4j:slf4j-api'
    compileOnly 'io.micrometer:micrometer-core'
}
